In [737]:
import numpy as numpy
import pandas as pandas
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegressionCV
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer

In [738]:
trainCSV = pandas.read_csv('../input/titanic/train.csv')
trainCSV.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [739]:
trainCSV.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [740]:
trainCSV_2 = trainCSV.drop(['Name', 'Ticket', 'Cabin'], axis=1)

In [741]:
trainCSV_2.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0            1         0       3    male  22.0      1      0   7.2500        S
1            2         1       1  female  38.0      1      0  71.2833        C
2            3         1       3  female  26.0      0      0   7.9250        S
3            4         1       1  female  35.0      1      0  53.1000        S
4            5         0       3    male  35.0      0      0   8.0500        S

In [742]:
model = SimpleImputer(strategy='mean')

In [743]:
CSVnum = trainCSV_2.drop(['Embarked', 'Sex'], axis=1) 

In [744]:
model.fit(CSVnum)

SimpleImputer()

In [745]:
model.statistics_

array([4.46000000e+02, 3.83838384e-01, 2.30864198e+00, 2.96991176e+01,
       5.23007856e-01, 3.81593715e-01, 3.22042080e+01])

In [746]:
dataFrameX = model.transform(CSVnum)  
dataFrameX[:5, :]

array([[ 1.    ,  0.    ,  3.    , 22.    ,  1.    ,  0.    ,  7.25  ],
       [ 2.    ,  1.    ,  1.    , 38.    ,  1.    ,  0.    , 71.2833],
       [ 3.    ,  1.    ,  3.    , 26.    ,  0.    ,  0.    ,  7.925 ],
       [ 4.    ,  1.    ,  1.    , 35.    ,  1.    ,  0.    , 53.1   ],
       [ 5.    ,  0.    ,  3.    , 35.    ,  0.    ,  0.    ,  8.05  ]])

In [747]:
CSVTransform = pandas.DataFrame(dataFrameX, columns=CSVnum.columns, index=CSVnum.index)

In [748]:
CSVTransform.head()

PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
0          1.0       0.0     3.0  22.0    1.0    0.0   7.2500
1          2.0       1.0     1.0  38.0    1.0    0.0  71.2833
2          3.0       1.0     3.0  26.0    0.0    0.0   7.9250
3          4.0       1.0     1.0  35.0    1.0    0.0  53.1000
4          5.0       0.0     3.0  35.0    0.0    0.0   8.0500

In [749]:
CSVTransform.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    float64
 1   Survived     891 non-null    float64
 2   Pclass       891 non-null    float64
 3   Age          891 non-null    float64
 4   SibSp        891 non-null    float64
 5   Parch        891 non-null    float64
 6   Fare         891 non-null    float64
dtypes: float64(7)
memory usage: 48.9 KB


In [750]:
dataFrameX = CSVTransform.drop('Survived', axis=1)
dataFrameY = CSVTransform['Survived'].copy()

In [751]:
dataFrameX.head()

PassengerId  Pclass   Age  SibSp  Parch     Fare
0          1.0     3.0  22.0    1.0    0.0   7.2500
1          2.0     1.0  38.0    1.0    0.0  71.2833
2          3.0     3.0  26.0    0.0    0.0   7.9250
3          4.0     1.0  35.0    1.0    0.0  53.1000
4          5.0     3.0  35.0    0.0    0.0   8.0500

In [752]:
dataFrameY

0      0.0
1      1.0
2      1.0
3      1.0
4      0.0
      ... 
886    0.0
887    1.0
888    0.0
889    1.0
890    0.0
Name: Survived, Length: 891, dtype: float64

In [753]:
trainDataframeX, testDataframeX, trainDataframeY, testDataframeY = train_test_split(dataFrameX, dataFrameY, test_size=0.20, random_state=42)

In [754]:
LogReg = LogisticRegression(max_iter=200,random_state=42).fit(trainDataframeX, trainDataframeY) 

In [755]:
LogReg.predict(testDataframeX)

array([0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0.,
       1., 1., 1., 0., 0., 0., 0., 1., 0.])

In [756]:
LogRegCV = LogisticRegressionCV(cv=5, max_iter=300).fit(trainDataframeX, trainDataframeY) # choosing cross validate = 5 fold

In [757]:
LogRegCV.predict(testDataframeX)

array([0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0.,
       1., 1., 1., 0., 0., 0., 0., 0., 0.])

In [758]:
LogRegCV.score(testDataframeX, testDataframeY)

0.7430167597765364

In [759]:
OrdinalEncoder = OrdinalEncoder()
titanicSex = numpy.c_[trainCSV_2['Sex']] # It will give us 2-D array

In [760]:
sexEncoded = OrdinalEncoder.fit_transform(titanicSex)
sexEncoded[:5]

array([[1.],
       [0.],
       [0.],
       [0.],
       [1.]])

In [761]:
CSVTransform['Sex'] = sexEncoded

In [762]:
CSVTransform.head()

PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare  Sex
0          1.0       0.0     3.0  22.0    1.0    0.0   7.2500  1.0
1          2.0       1.0     1.0  38.0    1.0    0.0  71.2833  0.0
2          3.0       1.0     3.0  26.0    0.0    0.0   7.9250  0.0
3          4.0       1.0     1.0  35.0    1.0    0.0  53.1000  0.0
4          5.0       0.0     3.0  35.0    0.0    0.0   8.0500  1.0

In [763]:
DataFrameNewX = CSVTransform.drop(['Survived'], axis=1)
DataFrameNewY = CSVTransform['Survived'].copy()

In [764]:
trainDataFrameNewX, testDataFrameNewX, trainDataFrameNewY, testDataFrameNewY = train_test_split(DataFrameNewX, DataFrameNewY, test_size=0.30, random_state=42)
trainDataFrameNewX.head()

PassengerId  Pclass        Age  SibSp  Parch     Fare  Sex
445        446.0     1.0   4.000000    0.0    2.0  81.8583  1.0
650        651.0     3.0  29.699118    0.0    0.0   7.8958  1.0
172        173.0     3.0   1.000000    1.0    1.0  11.1333  0.0
450        451.0     2.0  36.000000    1.0    2.0  27.7500  1.0
314        315.0     2.0  43.000000    1.0    1.0  26.2500  1.0

In [765]:
LogReg = LogisticRegression(max_iter=200).fit(trainDataFrameNewX, trainDataFrameNewY)
LogReg.predict(testDataFrameNewX)

array([0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
       0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 0., 1., 0., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0.,
       0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1.,
       0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1.,
       1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
       1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
       0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 0.,
       0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0.,
       1., 0., 0., 0., 1.

In [766]:
LogReg.score(testDataFrameNewX, testDataFrameNewY)

0.8097014925373134

In [767]:
testCSV = pandas.read_csv('../input/titanic/test.csv')
testCSV.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [768]:
testCSV = testCSV.drop(['Name', 'Ticket','Cabin', 'Embarked'], axis=1)

In [769]:
sexCatTestCSV = numpy.c_[testCSV['Sex']]
testCSVSexEncoded = OrdinalEncoder.fit_transform(sexCatTestCSV)

In [770]:
testCSVSexEncoded[:5]

array([[1.],
       [0.],
       [1.],
       [1.],
       [0.]])

In [771]:
testCSVNumberAttribute = testCSV.drop(['Sex', 'PassengerId'], axis=1)
testPassengerId = testCSV['PassengerId'].copy()
testCSVNumberAttribute

Pclass   Age  SibSp  Parch      Fare
0         3  34.5      0      0    7.8292
1         3  47.0      1      0    7.0000
2         2  62.0      0      0    9.6875
3         3  27.0      0      0    8.6625
4         3  22.0      1      1   12.2875
..      ...   ...    ...    ...       ...
413       3   NaN      0      0    8.0500
414       1  39.0      0      0  108.9000
415       3  38.5      0      0    7.2500
416       3   NaN      0      0    8.0500
417       3   NaN      1      1   22.3583

[418 rows x 5 columns]

In [772]:
testCSVImputer = model.fit_transform(testCSVNumberAttribute)
testCSVImputer

array([[ 3.        , 34.5       ,  0.        ,  0.        ,  7.8292    ],
       [ 3.        , 47.        ,  1.        ,  0.        ,  7.        ],
       [ 2.        , 62.        ,  0.        ,  0.        ,  9.6875    ],
       ...,
       [ 3.        , 38.5       ,  0.        ,  0.        ,  7.25      ],
       [ 3.        , 30.27259036,  0.        ,  0.        ,  8.05      ],
       [ 3.        , 30.27259036,  1.        ,  1.        , 22.3583    ]])

In [773]:
testCSVImputer = pandas.DataFrame(testCSVImputer, columns=testCSVNumberAttribute.columns, index=testCSVNumberAttribute.index)
testCSVImputer.head()

Pclass   Age  SibSp  Parch     Fare
0     3.0  34.5    0.0    0.0   7.8292
1     3.0  47.0    1.0    0.0   7.0000
2     2.0  62.0    0.0    0.0   9.6875
3     3.0  27.0    0.0    0.0   8.6625
4     3.0  22.0    1.0    1.0  12.2875

In [774]:
testCSVImputer['Sex'] = testCSVSexEncoded
testCSVImputer['PassengerId'] = testPassengerId
testCSVImputer = testCSVImputer[['PassengerId', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex']]
testCSVImputer.head()

PassengerId  Pclass   Age  SibSp  Parch     Fare  Sex
0          892     3.0  34.5    0.0    0.0   7.8292  1.0
1          893     3.0  47.0    1.0    0.0   7.0000  0.0
2          894     2.0  62.0    0.0    0.0   9.6875  1.0
3          895     3.0  27.0    0.0    0.0   8.6625  1.0
4          896     3.0  22.0    1.0    1.0  12.2875  0.0

In [775]:
testSurvived = LogReg.predict(testCSVImputer)
testSurvived[:20]

array([0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0.,
       0., 1., 1.])

In [776]:
testCSVImputer['Survived'] = testSurvived

In [777]:
testCSVImputer['Survived'] = testCSVImputer['Survived'].astype(int)
testCSVImputer.head()

PassengerId  Pclass   Age  SibSp  Parch     Fare  Sex  Survived
0          892     3.0  34.5    0.0    0.0   7.8292  1.0         0
1          893     3.0  47.0    1.0    0.0   7.0000  0.0         0
2          894     2.0  62.0    0.0    0.0   9.6875  1.0         0
3          895     3.0  27.0    0.0    0.0   8.6625  1.0         0
4          896     3.0  22.0    1.0    1.0  12.2875  0.0         1

In [778]:
finalOutput = testCSVImputer.drop(['Pclass', 'Age', 'SibSp', 'Parch', 'Sex', 'Fare'], axis=1)
finalOutput.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         1

In [779]:
finalOutput.to_csv('titanicSurvivals.csv', index=False)